# Databricks notebook source
# MAGIC %md
# MAGIC # Process online serving logs
# MAGIC
# MAGIC **Session:** Monitoring & Retraining
# MAGIC
# MAGIC The serving endpoint has an AI Gateway inference table that captures every
# MAGIC request/response as raw JSON. That payload table cannot be profiled directly:
# MAGIC Lakehouse Monitoring's InferenceLog analysis needs one row per prediction with typed
# MAGIC `prediction` / `model_version` / `timestamp` / `label` columns. This notebook unpacks
# MAGIC the payload table into that shape so the online monitor can profile the traffic, as the
# MAGIC batch job does for the report.
# MAGIC
# MAGIC - **Read (personal):** `dev.<you>_fraud.fraud_serving_payload` (raw AI Gateway logs)
# MAGIC - **Write (personal):** `dev.<you>_fraud.fraud_serving_inference` (InferenceLog-shaped)
# MAGIC
# MAGIC > Online requests have no ground-truth label at inference time (fraud is confirmed
# MAGIC > later), so `is_fraud` is joined best-effort from gold and left null otherwise. The
# MAGIC > online monitor tracks drift immediately; quality fills in as labels land.
# MAGIC
# MAGIC Docs: [AI Gateway inference tables](https://learn.microsoft.com/azure/databricks/ai-gateway/)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Setup
# MAGIC
# MAGIC This notebook only reshapes what the AI Gateway already captured; it does not call the
# MAGIC endpoint. Traffic is generated by the serving lab, and AI Gateway logs can take up to
# MAGIC ~1 hour to land, so the most recent calls may not appear immediately.

# COMMAND ----------

dbutils.widgets.text("catalog_name", "dev")
dbutils.widgets.text("gold_schema", "fraud_gold")
dbutils.widgets.text("ml_schema", "")

catalog_name = dbutils.widgets.get("catalog_name")
gold_schema = dbutils.widgets.get("gold_schema")
ml_schema = dbutils.widgets.get("ml_schema")

from pyspark.sql import functions as F

# Interactive fallback: jobs pass the resolved personal schema; running standalone derives
# the same per-user name the bundle uses (dev_<short>_fraud) so runs stay isolated.
if not ml_schema:
    _user = spark.range(1).select(F.current_user()).first()[0]
    _short = "".join(c if c.isalnum() else "_" for c in _user.split("@")[0])
    ml_schema = f"dev_{_short}_fraud"

payload_table = f"{catalog_name}.{ml_schema}.fraud_serving_payload"
online_table = f"{catalog_name}.{ml_schema}.fraud_serving_inference"
gold_table = f"{catalog_name}.{gold_schema}.transactions_enriched"

print(f"Payload (raw): {payload_table}")
print(f"Online (out):  {online_table}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 1. Unpack the raw payloads into an inference log
# MAGIC Each payload row is one real-time call. The serving lab tagged every call with the
# MAGIC transaction's id as the `client_request_id` (the correlation id) and sent a single
# MAGIC record, so the response holds one prediction. Turn each row into one prediction row
# MAGIC carrying `transaction_id` (from `client_request_id`), the `prediction`, and the
# MAGIC request timestamp; keep `served_entity_id` to resolve the model version next.

# COMMAND ----------

# Unpack the AI Gateway payload table into one row per prediction. This is heavy Spark
# plumbing (guarding the delivery lag, from_json, explode), so it is provided; the label
# join and write at the end are the exercise.
from pyspark.sql import functions as F
from pyspark.sql import types as T

empty_schema = T.StructType(
    [
        T.StructField("transaction_id", T.LongType()),
        T.StructField("fraud_score", T.DoubleType()),
        T.StructField("prediction", T.IntegerType()),
        T.StructField("model_version", T.StringType()),
        T.StructField("scored_at", T.TimestampType()),
        T.StructField("is_fraud", T.IntegerType()),
        # Same feature columns as the batch table so both monitors are symmetric.
        T.StructField("amount", T.DoubleType()),
        T.StructField("credit_score", T.IntegerType()),
        T.StructField("credit_limit", T.DoubleType()),
        T.StructField("yearly_income", T.DoubleType()),
        T.StructField("current_age", T.IntegerType()),
        T.StructField("num_cards_issued", T.IntegerType()),
        T.StructField("is_night", T.BooleanType()),
        T.StructField("is_online", T.BooleanType()),
        T.StructField("is_high_risk_mcc", T.BooleanType()),
        T.StructField("amount_to_income_ratio", T.DoubleType()),
        T.StructField("amount_to_credit_limit_ratio", T.DoubleType()),
    ]
)

# The AI Gateway inference table starts as a placeholder (only databricks_request_id) and
# only gains its real columns once a request/response has been logged. Treat a
# missing table OR a not-yet-populated schema the same way: write an empty table and exit.
required_cols = {"status_code", "response", "client_request_id", "request_time", "served_entity_id"}
payload_cols = (
    set(spark.table(payload_table).columns) if spark.catalog.tableExists(payload_table) else set()
)
if not required_cols.issubset(payload_cols):
    spark.createDataFrame([], empty_schema).write.mode("overwrite").option(
        "overwriteSchema", "true"
    ).saveAsTable(online_table)
    dbutils.notebook.exit(
        f"Payload table {payload_table} not ready yet (AI Gateway delivery lag): "
        f"wrote empty {online_table}."
    )

raw = (
    spark.read.table(payload_table)
    .where(F.col("status_code") == 200)
    .withColumn("resp", F.from_json("response", "predictions array<double>"))
    .withColumn("n", F.size("resp.predictions"))
)

exploded = raw.select(
    "client_request_id",
    "n",
    "served_entity_id",
    F.col("request_time").alias("scored_at"),
    F.explode("resp.predictions").alias("prediction"),
).select(
    # client_request_id is one id per request, so it maps cleanly only to single-record
    # (real-time) calls; guard on n == 1 (null id / batched requests stay unlabelled but
    # still contribute their prediction to drift).
    F.when(F.col("n") == 1, F.col("client_request_id").cast("long")).alias("transaction_id"),
    # The endpoint serves a fraud PROBABILITY. Keep it as fraud_score and threshold it to
    # a 0/1 class for the classification monitor (prediction must match the INT label).
    F.col("prediction").alias("fraud_score"),
    (F.col("prediction") >= F.lit(0.5)).cast("int").alias("prediction"),
    "served_entity_id",
    "scored_at",
)

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2. Resolve the model version (instructor-provided)
# MAGIC The payload logs the opaque `served_entity_id`, not the friendly version number. The
# MAGIC `system.serving.served_entities` system table maps one to the other (the documented
# MAGIC join), so the online monitor groups metrics by the same `model_version` as the batch
# MAGIC monitor. Falls back to the raw id if that system table isn't readable.

# COMMAND ----------

try:
    served = (
        spark.read.table("system.serving.served_entities")
        .select("served_entity_id", F.col("entity_version").cast("string").alias("model_version"))
        .dropDuplicates(["served_entity_id"])
    )
    exploded = exploded.join(served, on="served_entity_id", how="left").withColumn(
        "model_version", F.coalesce("model_version", F.col("served_entity_id"))
    )
except Exception as exc:
    print(f"(system.serving.served_entities not available: {exc}); using served_entity_id")
    exploded = exploded.withColumnRenamed("served_entity_id", "model_version")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 3. Best-effort label join and persist
# MAGIC
# MAGIC Attach the confirmed label where available (null otherwise, online labels lag), then
# MAGIC overwrite the online inference table. Same schema as the batch `fraud_predictions`
# MAGIC table, so both monitors line up.

# COMMAND ----------

# Attach the confirmed label AND the same feature columns as the batch fraud_predictions
# table, so the two monitors are symmetric and track drift on every model feature. The serving
# payload only logs raw inputs, so the features the model used are resolved by transaction_id
# from the gold source: entity features are columns, and the on-demand features are computed
# with the same UC functions the model uses (no train/serve skew). The join is provided.
schema_fqn = f"{catalog_name}.{ml_schema}"
gold_raw = spark.read.table(gold_table).select(
    "transaction_id",
    F.col("amount").cast("double").alias("amount"),
    F.col("credit_score").cast("int").alias("credit_score"),
    F.col("credit_limit").cast("double").alias("credit_limit"),
    F.col("yearly_income").cast("double").alias("yearly_income"),
    F.col("current_age").cast("int").alias("current_age"),
    F.col("num_cards_issued").cast("int").alias("num_cards_issued"),
    "transaction_hour",
    "use_chip",
    "mcc",
    F.col("is_fraud").cast("int").alias("is_fraud"),
)

online = (
    exploded.join(gold_raw, on="transaction_id", how="left")
    .withColumn("is_night", F.expr(f"{schema_fqn}.ff_is_night(transaction_hour)"))
    .withColumn("is_online", F.expr(f"{schema_fqn}.ff_is_online(use_chip)"))
    .withColumn("is_high_risk_mcc", F.expr(f"{schema_fqn}.ff_is_high_risk_mcc(mcc)"))
    .withColumn(
        "amount_to_income_ratio",
        F.expr(f"{schema_fqn}.ff_amount_to_income_ratio(amount, yearly_income)"),
    )
    .withColumn(
        "amount_to_credit_limit_ratio",
        F.expr(f"{schema_fqn}.ff_amount_to_credit_limit_ratio(amount, credit_limit)"),
    )
    .select(
        "transaction_id",
        "fraud_score",
        "prediction",
        "model_version",
        "scored_at",
        "is_fraud",
        "amount",
        "credit_score",
        "credit_limit",
        "yearly_income",
        "current_age",
        "num_cards_issued",
        "is_night",
        "is_online",
        "is_high_risk_mcc",
        "amount_to_income_ratio",
        "amount_to_credit_limit_ratio",
    )
)

# TODO: write the online inference table so the online monitor can read it
# HINT: online.write.mode("overwrite").option("overwriteSchema", "true").saveAsTable(online_table)
# HINT: overwrite (not append): this notebook rebuilds the table from the payloads each run.
# <-- Your code here

# COMMAND ----------

# MAGIC %md
# MAGIC ## Recap
# MAGIC - The AI Gateway captured online traffic automatically; this notebook only reshaped it.
# MAGIC - `transaction_id` came from the `client_request_id` correlation id the caller set:
# MAGIC   the clean way to join model outputs back to confirmed-fraud labels later.
# MAGIC - `fraud_serving_inference` now matches the batch `fraud_predictions` schema, so the
# MAGIC   online and batch monitors are symmetric and comparable.
# MAGIC - Online labels lag, so the online monitor leads with drift; the batch monitor carries
# MAGIC   quality.

# COMMAND ----------

display(spark.read.table(online_table).limit(10))
